### ISSUE TITLE
Reminders: Handle West Coast for TV times

### ISSUE THREAD

**Issue by rayyamartino** [mcongrove/ForekastMobile#33]
Introduce reminder logic to handle tv timezones (happens live twice, once for eastern/central, once for pacific)

Now I'm wondering if this is even possible, oh no... If it is, remember that Alaskan and Hawaiian tune in to the live showing of the Pacific showing, which means it's a few hours earlier for them.

**Comment by mcongrove** [comment]
So if the offset is ET or CT it's fine as-is, otherwise subtract 2 hours for all other US timezones?
